
baseurl = "https://khannm.netlify.com"
title = "Mohammad Khan"
theme = "coder"
languagecode = "en"

publishDir = "dist"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Mohammad Khan"
    description = "Mohammad Khan's personal website"
    keywords = "blog,developer,personal"
    info = "Developer and Keyboard Enthusiast"
    avatarurl = "images/me.jpg"
    footercontent = "Favourite Quote:\"It’s hardware that makes a machine fast.  It’s software that makes a fast machine slow.\" - Craig Bruce"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    rtl = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/ilikerustoo/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab"
#     weight = 2
#     url = "https://gitlab.com/johndoe/"
# [[params.social]]
#     name = "Twitter"
#     icon = "fab fa-twitter"
#     weight = 3
#     url = "https://twitter.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/khannm1/"
# [[params.social]]
#     name = "Medium"
#     icon = "fab fa-medium"
#     weight = 5
#     url = "https://medium.com/@johndoe"
[[params.social]]
    name = "Stack Overflow"
    icon = "fab fa-stack-overflow"
    weight = 3
    url = "https://stackoverflow.com/users/10490331/mohammad-khan?tab=profile"


[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About Me"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Resume"
    weight = 4
    url = "/resume.files/resume.pdf"
# [[menu.main]]
#     name = "Contact me"
#     weight = 5
#     url = "/contact/"


[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Mohammad Khan"

        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "Mohammad Khan"
        info = "Developer and Keyboard Enthusiast"
        description = "Mohammad Khan's personal website"
        keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About Me"
        weight = 1.0
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2.0
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"
        [[languages.en.menu.main]]
        name = "Resume"
        weight = 4
        url = "/resume.files/resume.pdf"
        # [[languages.en.menu.main]]
        # name = "Contacts me"
        # weight = 5
        # url = "/contact/"


    # [languages.pl]
    #     languagename = "Polski"
    #     title = "John Doe po polsku"
    #
    #     [languages.pl.params]
    #         author = "John Doe"
    #         description = "Strona domowa John'a Doe"
    #         keywords = "blog,developer,strona domowa"
    #         info = "Full Stack DevOps i Magik"
    #
    #     [languages.pl.menu]
    #
    #         [[languages.pl.menu.main]]
    #         name = "O mnie"
    #         weight = 1.0
    #         url = "/pl/about/"
    #
    #         [[languages.pl.menu.main]]
    #         name = "Blog"
    #         weight = 2.0
    #         url = "/pl/posts/"
    #
    #         [[languages.pl.menu.main]]
    #         name = "projektowanie"
    #         weight = 3
    #         url = "/projektowanie/"
    #         [[languages.pl.menu.main]]
    #         name = "kontakt"
    #         weight = 5
    #         url = "/kontakt/"
